# Generated by Django 3.2.3 on 2021-05-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_albom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albom',
            old_name='author',
            new_name='user',
        ),
    ]
