# Generated by Django 3.2.3 on 2021-05-29 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_rename_author_albom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_gallery', to='webapp.gallery', verbose_name='фото')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_choice_gallery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'choice',
                'verbose_name_plural': 'choices',
                'db_table': 'choice_gallery',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAlbom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_albom', to='webapp.albom', verbose_name='Альбом')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_choice_albom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'choice',
                'verbose_name_plural': 'choices',
                'db_table': 'choice_albom',
            },
        ),
    ]
